# Generated by Django 5.2.12 on 2026-03-30 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('remediated', 'Remediated'), ('accepted', 'Risk Accepted')], default='open', max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('attack_vector', models.CharField(choices=[('N', 'Network'), ('A', 'Adjacent'), ('L', 'Local'), ('P', 'Physical')], default='N', max_length=1)),
                ('attack_complexity', models.CharField(choices=[('L', 'Low'), ('H', 'High')], default='L', max_length=1)),
                ('privileges_required', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], default='N', max_length=1)),
                ('user_interaction', models.CharField(choices=[('N', 'None'), ('R', 'Required')], default='N', max_length=1)),
                ('confidentiality_impact', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('N', 'None')], default='N', max_length=1)),
                ('integrity_impact', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('N', 'None')], default='N', max_length=1)),
                ('availability_impact', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('N', 'None')], default='N', max_length=1)),
                ('description', models.TextField()),
                ('affected_hosts', models.TextField(blank=True, help_text='One host per line')),
                ('proof_of_concept', models.TextField(blank=True, help_text='Steps to reproduce')),
                ('remediation', models.TextField(blank=True)),
                ('references', models.TextField(blank=True, help_text='CVE IDs, URLs — one per line')),
                ('cwe_id', models.CharField(blank=True, help_text='e.g. CWE-79', max_length=20)),
                ('tool_source', models.CharField(blank=True, help_text='e.g. Nmap, Burp, Manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='engagements.engagement')),
                ('found_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='vulns.finding')),
            ],
            options={
                'verbose_name_plural': 'evidence',
            },
        ),
    ]
