# Generated by Django 5.0.14 on 2026-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='endpoint',
            field=models.CharField(blank=True, help_text='API endpoint or path, e.g. /api/v1/login', max_length=500),
        ),
        migrations.AddField(
            model_name='finding',
            name='host',
            field=models.CharField(blank=True, help_text='e.g. api.example.com', max_length=300),
        ),
        migrations.AddField(
            model_name='finding',
            name='http_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], help_text='HTTP method used', max_length=10),
        ),
        migrations.AddField(
            model_name='finding',
            name='parameter',
            field=models.CharField(blank=True, help_text='Vulnerable parameter, e.g. username, id', max_length=300),
        ),
        migrations.AddField(
            model_name='finding',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 443, 8080', null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='url',
            field=models.URLField(blank=True, help_text='Full URL where the issue was found', max_length=2000),
        ),
        migrations.AlterField(
            model_name='finding',
            name='affected_hosts',
            field=models.TextField(blank=True, help_text='Additional affected hosts — one per line'),
        ),
    ]
