# Generated by Django 5.2.13 on 2026-06-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0011_evidence_reviewed_evidence_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='request_response',
            field=models.TextField(blank=True),
        ),
    ]
