# Generated by Django 5.2.13 on 2026-04-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='credential',
            new_name='credentials_engagem_247cd3_idx',
            old_name='credentials_engage_created_idx',
        ),
    ]
