# Generated by Django 5.2.13 on 2026-04-16 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_timesta_40aa9a_idx',
            old_name='accounts_au_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_action_918219_idx',
            old_name='accounts_au_action_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system/failed login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target',
            field=models.CharField(blank=True, help_text='Subject of the action — username, engagement name, report id, etc.', max_length=300),
        ),
    ]
