# Generated by Django 5.2.13 on 2026-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_auditlog_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_create', 'User created'), ('user_update', 'User updated'), ('user_delete', 'User deleted'), ('user_role_change', 'User role changed'), ('engagement_create', 'Engagement created'), ('engagement_delete', 'Engagement deleted'), ('report_download', 'Report downloaded'), ('report_generate', 'Report generated'), ('login_failed', 'Login failed'), ('mfa_enabled', 'MFA enabled'), ('mfa_disabled', 'MFA disabled'), ('mfa_challenge_failed', 'MFA challenge failed')], max_length=40),
        ),
    ]
