# Generated by Django 5.2.13 on 2026-04-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_apikey_and_api_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_create', 'User created'), ('user_update', 'User updated'), ('user_delete', 'User deleted'), ('user_role_change', 'User role changed'), ('engagement_create', 'Engagement created'), ('engagement_delete', 'Engagement deleted'), ('report_downloaded', 'Report downloaded'), ('report_generated', 'Report generated'), ('login_failed', 'Login failed'), ('login_success', 'Login succeeded'), ('login_locked', 'Login locked out'), ('logout', 'Logout'), ('mfa_enabled', 'MFA enabled'), ('mfa_disabled', 'MFA disabled'), ('mfa_challenge_failed', 'MFA challenge failed'), ('password_change', 'Password changed'), ('credential_create', 'Credential created'), ('credential_delete', 'Credential deleted'), ('credential_reveal', 'Credential revealed'), ('evidence_download', 'Evidence downloaded'), ('invitation_sent', 'Invitation sent'), ('invitation_accepted', 'Invitation accepted'), ('api_key_issued', 'API key issued'), ('api_key_revoked', 'API key revoked'), ('comment_post', 'Comment posted'), ('comment_edit', 'Comment edited'), ('comment_delete', 'Comment deleted')], max_length=40),
        ),
    ]
