# Generated by Django 5.2.12 on 2026-03-30 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('engagement_type', models.CharField(choices=[('external', 'External Pentest'), ('internal', 'Internal Pentest'), ('webapp', 'Web Application'), ('api', 'API Assessment'), ('mobile', 'Mobile Application'), ('wireless', 'Wireless Assessment'), ('social_engineering', 'Social Engineering'), ('red_team', 'Red Team')], max_length=30)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('recon', 'Reconnaissance'), ('scanning', 'Scanning'), ('exploitation', 'Exploitation'), ('post_exploitation', 'Post-Exploitation'), ('reporting', 'Reporting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('in_scope', models.TextField(blank=True, help_text='One target per line (IPs, domains, URLs)')),
                ('out_of_scope', models.TextField(blank=True, help_text='Excluded targets, one per line')),
                ('rules_of_engagement', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_engagements', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_engagements', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EngagementNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
