# Generated by Django 5.2.13 on 2026-06-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0006_client_primary_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g. Financial services, E-commerce, Healthcare', max_length=120),
        ),
    ]
